name: tests
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        fhir-sequence: [STU3, R4B, R5, R4]
        include:
          - fhir-sequence: STU3
            fhir-resources-dependency: ^7.0.0
          - fhir-sequence: R4B
            fhir-resources-dependency: ^7.0.0
          - fhir-sequence: R5
            fhir-resources-dependency: ^7.0.0
          - fhir-sequence: R4
            fhir-resources-dependency: ~6.4.0
    steps:
    - uses: actions/checkout@v4
    - name: Install Poetry
      run: pipx install poetry
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'
    - name: Install Python packages
      run: |
        poetry add "fhir.resources"@${{ matrix.fhir-resources-dependency }}
        poetry install
    - name: Run tests
      env:
        FHIR_SEQUENCE: ${{ matrix.fhir-sequence }}
      run: poetry run pytest
